# configs/__init__.py

# This file makes the 'configs' directory a Python package and exports all configurations.

from .base_config import OPENAI_API_KEY, PROJECT_ROOT
from .paths_config import (
    ASSETS_DIR, FONTS_DIR, BUNDLED_FONT_PATH,
    OUTPUT_DIR, RAW_PANELS_DIR, SIZED_PANELS_DIR,
    CAPTIONED_PANELS_DIR, COMIC_PAGES_DIR
)
from .image_opts_config import (
    PANEL_OUTPUT_SIZE, PAGE_WIDTH, PAGE_HEIGHT, MARGIN, PANEL_SIZE
)
from .text_style_config import (
    CAPTION_BACKGROUND_COLOR, CAPTION_TEXT_COLOR, CAPTION_PADDING,
    CAPTION_MARGIN, MAX_CAPTION_HEIGHT_RATIO, LINE_SPACING,
    CAPTION_CORNER_RADIUS, NARRATOR_BACKGROUND_COLOR,
    MAX_FONT_SIZE, DEFAULT_FONT_SIZE, MIN_FONT_SIZE,
    SFX_TEXT_COLOR, SFX_FONT_PATH
)
from .ui_options_config import (
    DEFAULT_LAYOUT_STYLE, SUPPORTED_LAYOUT_STYLES,
    DEFAULT_STYLE_PRESET, SUPPORTED_STYLE_PRESETS,
    DEFAULT_GENRE_PRESET, SUPPORTED_GENRE_PRESETS
)
from .llm_api_config import (
    USE_BEDROCK_IMAGE_GENERATION, BEDROCK_AWS_REGION, BEDROCK_IMAGE_MODEL_ID
)
from .story_elements_config import CHARACTER_DESCRIPTION
from .prompt_styles import (
    STYLE_CONFIGS, DEFAULT_STYLE_KEYWORDS, DEFAULT_LIGHTING_KEYWORDS,
    DEFAULT_ADDITIONAL_DETAILS, DEFAULT_PROMPT_SUFFIX
)


__all__ = [
    # from base_config
    "OPENAI_API_KEY", "PROJECT_ROOT",
    # from paths_config
    "ASSETS_DIR", "FONTS_DIR", "BUNDLED_FONT_PATH",
    "OUTPUT_DIR", "RAW_PANELS_DIR", "SIZED_PANELS_DIR",
    "CAPTIONED_PANELS_DIR", "COMIC_PAGES_DIR",
    # from image_opts_config
    "PANEL_OUTPUT_SIZE", "PAGE_WIDTH", "PAGE_HEIGHT", "MARGIN", "PANEL_SIZE",
    # from text_style_config
    "CAPTION_BACKGROUND_COLOR", "CAPTION_TEXT_COLOR", "CAPTION_PADDING",
    "CAPTION_MARGIN", "MAX_CAPTION_HEIGHT_RATIO", "LINE_SPACING",
    "CAPTION_CORNER_RADIUS", "NARRATOR_BACKGROUND_COLOR",
    "MAX_FONT_SIZE", "DEFAULT_FONT_SIZE", "MIN_FONT_SIZE",
    "SFX_TEXT_COLOR", "SFX_FONT_PATH",
    # from ui_options_config
    "DEFAULT_LAYOUT_STYLE", "SUPPORTED_LAYOUT_STYLES",
    "DEFAULT_STYLE_PRESET", "SUPPORTED_STYLE_PRESETS",
    "DEFAULT_GENRE_PRESET", "SUPPORTED_GENRE_PRESETS",
    # from llm_api_config
    "USE_BEDROCK_IMAGE_GENERATION", "BEDROCK_AWS_REGION", "BEDROCK_IMAGE_MODEL_ID",
    # from story_elements_config
    "CHARACTER_DESCRIPTION",
    # from prompt_styles
    "STYLE_CONFIGS", "DEFAULT_STYLE_KEYWORDS", "DEFAULT_LIGHTING_KEYWORDS",
    "DEFAULT_ADDITIONAL_DETAILS", "DEFAULT_PROMPT_SUFFIX"
]
